### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ringostarr80**

### CODE REVIEW

**Comment by ROBERT-MCDOWELL** [comment]
whi did you close it?

**Comment by ringostarr80** [comment]
It was unintended. I wanted to make a PR on my main branch.

**Comment by ROBERT-MCDOWELL** [comment]
ok but why not to let this PR open here so it will be sync to your branch?

**Comment by ringostarr80** [comment]
Because I want to do a complete rewrite/refactoring of the whole codebase.
But it's still in a very early stage.

The codebase was not touched for a long time, so it has no clear CodeStyle or checks that I want to add with PHPCS and PHPStan. I also want to add some more modern test with Codeception or something like that.

Also, I don't believe, that such a great refactoring, will be merged into this repository. It also seems to be abandoned to me.

If you think that I'm wrong, we could reopen this PR and give it try?

**Comment by ROBERT-MCDOWELL** [comment]
what you can do is too finalize your modifications, then once you are sure it's stable resend a PR here and see if there are some that will merge it. if not, so it's good to go to your fork as a a main repo so.

**Comment by ringostarr80** [comment]
Yes, this sounds to be a good option!

**Pull request closed without merging**
